kind = "web"
previewPath = "/"
title = "Máy In Nhiệt - ThermalPrint"
version = "1.0.0"
id = "artifacts/thermal-print"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22646

[services.development]
run = "pnpm --filter @workspace/thermal-print run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/thermal-print", "run", "build" ]
run = "pnpm --filter @workspace/thermal-print run start"

[services.env]
PORT = "22646"
